package backend.optimize;

public class ResultAverager {
    private int count = 0;
    private int windowCount;
    private int tableCount;
    private int totalStudents;
    private int requestedPopulation;
    private int openDuration;
    private double probSolo;
    private double avgMealPrice;
    private double windowCostPerHour;
    private double tableCost;
    private double lostStudentPenalty;
    private String simulationModeCode;
    private String mealPeriodCode;
    private int minWindowCount;
    private int maxWindowCount;
    private int minTableCount;
    private int maxTableCount;
    private long baseRandomSeed;
    private int repeatTimes;
    private double sumArrived;
    private double sumServed;
    private double sumAbandoned;
    private double sumFinished;
    private double sumAvgWaitSeconds;
    private double sumAvgWaitMinutes;
    private double maxP95WaitSeconds;
    private double maxP95WaitMinutes;
    private double sumAvgSeatWaitSeconds;
    private double sumAvgSeatWaitMinutes;
    private double maxP95SeatWaitSeconds;
    private double maxP95SeatWaitMinutes;
    private double sumAvgTotalStaySeconds;
    private double sumAvgTotalStayMinutes;
    private double maxP95TotalStaySeconds;
    private double maxP95TotalStayMinutes;
    private int maxQueueLength;
    private int maxWaitingSeatCount;
    private double sumAvgQueueLength;
    private double sumSeatUtilization;
    private double sumTableUtilization;
    private double sumWindowUtilization;
    private double sumFinishRate;
    private double sumAbandonRate;
    private double sumGrossRevenue;
    private double sumWindowOperatingCost;
    private double sumTableOperatingCost;
    private double sumLostOpportunityCost;
    private double sumNetProfit;
    private double sumRuntimeMs;

    public void add(SimRunResult r) {
        if (count == 0) {
            windowCount = r.windowCount;
            tableCount = r.tableCount;
            totalStudents = r.totalStudents;
            requestedPopulation = r.requestedPopulation;
            openDuration = r.openDuration;
            probSolo = r.probSolo;
            avgMealPrice = r.avgMealPrice;
            windowCostPerHour = r.windowCostPerHour;
            tableCost = r.tableCost;
            lostStudentPenalty = r.lostStudentPenalty;
            simulationModeCode = r.simulationModeCode;
            mealPeriodCode = r.mealPeriodCode;
            minWindowCount = r.minWindowCount;
            maxWindowCount = r.maxWindowCount;
            minTableCount = r.minTableCount;
            maxTableCount = r.maxTableCount;
            baseRandomSeed = r.baseRandomSeed;
            repeatTimes = r.repeatTimes;
        }
        count++;
        sumArrived += r.arrivedStudents;
        sumServed += r.servedStudents;
        sumAbandoned += r.abandonedStudents;
        sumFinished += r.finishedStudents;
        sumAvgWaitSeconds += r.avgWaitTimeSeconds;
        sumAvgWaitMinutes += r.avgWaitTimeMinutes;
        maxP95WaitSeconds = Math.max(maxP95WaitSeconds, r.p95WaitTimeSeconds);
        maxP95WaitMinutes = Math.max(maxP95WaitMinutes, r.p95WaitTimeMinutes);
        sumAvgSeatWaitSeconds += r.avgSeatWaitTimeSeconds;
        sumAvgSeatWaitMinutes += r.avgSeatWaitTimeMinutes;
        maxP95SeatWaitSeconds = Math.max(maxP95SeatWaitSeconds, r.p95SeatWaitTimeSeconds);
        maxP95SeatWaitMinutes = Math.max(maxP95SeatWaitMinutes, r.p95SeatWaitTimeMinutes);
        sumAvgTotalStaySeconds += r.avgTotalStayTimeSeconds;
        sumAvgTotalStayMinutes += r.avgTotalStayTimeMinutes;
        maxP95TotalStaySeconds = Math.max(maxP95TotalStaySeconds, r.p95TotalStayTimeSeconds);
        maxP95TotalStayMinutes = Math.max(maxP95TotalStayMinutes, r.p95TotalStayTimeMinutes);
        maxQueueLength = Math.max(maxQueueLength, r.maxQueueLength);
        maxWaitingSeatCount = Math.max(maxWaitingSeatCount, r.maxWaitingSeatCount);
        sumAvgQueueLength += r.avgQueueLength;
        sumSeatUtilization += r.seatUtilization;
        sumTableUtilization += r.tableUtilization;
        sumWindowUtilization += r.windowUtilization;
        sumFinishRate += r.finishRate;
        sumAbandonRate += r.abandonRate;
        sumGrossRevenue += r.grossRevenue;
        sumWindowOperatingCost += r.windowOperatingCost;
        sumTableOperatingCost += r.tableOperatingCost;
        sumLostOpportunityCost += r.lostOpportunityCost;
        sumNetProfit += r.netProfit;
        sumRuntimeMs += r.runtimeMs;
    }

    public SimRunResult average() {
        if (count == 0) {
            throw new IllegalStateException("没有可平均的仿真结果");
        }
        SimRunResult r = new SimRunResult();
        r.windowCount = windowCount;
        r.tableCount = tableCount;
        r.totalStudents = totalStudents;
        r.requestedPopulation = requestedPopulation;
        r.openDuration = openDuration;
        r.probSolo = probSolo;
        r.avgMealPrice = avgMealPrice;
        r.windowCostPerHour = windowCostPerHour;
        r.tableCost = tableCost;
        r.lostStudentPenalty = lostStudentPenalty;
        r.simulationModeCode = simulationModeCode;
        r.mealPeriodCode = mealPeriodCode;
        r.minWindowCount = minWindowCount;
        r.maxWindowCount = maxWindowCount;
        r.minTableCount = minTableCount;
        r.maxTableCount = maxTableCount;
        r.baseRandomSeed = baseRandomSeed;
        r.repeatTimes = repeatTimes;
        r.arrivedStudents = (int) Math.round(sumArrived / count);
        r.servedStudents = (int) Math.round(sumServed / count);
        r.abandonedStudents = (int) Math.round(sumAbandoned / count);
        r.finishedStudents = (int) Math.round(sumFinished / count);
        r.avgWaitTimeSeconds = sumAvgWaitSeconds / count;
        r.avgWaitTimeMinutes = sumAvgWaitMinutes / count;
        r.p95WaitTimeSeconds = maxP95WaitSeconds;
        r.p95WaitTimeMinutes = maxP95WaitMinutes;
        r.avgSeatWaitTimeSeconds = sumAvgSeatWaitSeconds / count;
        r.avgSeatWaitTimeMinutes = sumAvgSeatWaitMinutes / count;
        r.p95SeatWaitTimeSeconds = maxP95SeatWaitSeconds;
        r.p95SeatWaitTimeMinutes = maxP95SeatWaitMinutes;
        r.avgTotalStayTimeSeconds = sumAvgTotalStaySeconds / count;
        r.avgTotalStayTimeMinutes = sumAvgTotalStayMinutes / count;
        r.p95TotalStayTimeSeconds = maxP95TotalStaySeconds;
        r.p95TotalStayTimeMinutes = maxP95TotalStayMinutes;
        r.maxQueueLength = maxQueueLength;
        r.maxWaitingSeatCount = maxWaitingSeatCount;
        r.avgQueueLength = sumAvgQueueLength / count;
        r.seatUtilization = sumSeatUtilization / count;
        r.tableUtilization = sumTableUtilization / count;
        r.windowUtilization = sumWindowUtilization / count;
        r.finishRate = sumFinishRate / count;
        r.abandonRate = sumAbandonRate / count;
        r.grossRevenue = sumGrossRevenue / count;
        r.windowOperatingCost = sumWindowOperatingCost / count;
        r.tableOperatingCost = sumTableOperatingCost / count;
        r.lostOpportunityCost = sumLostOpportunityCost / count;
        r.netProfit = sumNetProfit / count;
        r.runtimeMs = Math.round(sumRuntimeMs / count);
        return r;
    }
}
